# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: backend-db
    volumes:
      - ./dbvolume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: admintestpass
      MYSQL_DATABASE: vrstore
    ports:
      - "3306:3306"
      - "33060:33060"